[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Configure secrets scanning to ignore Supabase public keys
# These are safe to expose as they're designed to be public-facing
[build.processing]
  skip_processing = false

# Disable secrets scanning for known safe environment variables
[build.processing.secrets]
  # Supabase anon key and URL are safe to expose (they're public-facing)
  omit_keys = ["VITE_SUPABASE_ANON_KEY", "VITE_SUPABASE_URL"]
  
# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
